<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-15 09:58
=======
# Generated by Django 5.2.5 on 2025-09-11 12:33
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='University',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('universityId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('establishedYear', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('established_year', models.IntegerField()),
            ],
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hod', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
            options={
                'abstract': False,
            },
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
                ('title', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
<<<<<<< HEAD
            options={
                'abstract': False,
            },
=======
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
<<<<<<< HEAD
            options={
                'abstract': False,
            },
=======
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('enrollmentYear', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
<<<<<<< HEAD
            options={
                'abstract': False,
            },
=======
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to='core.subject')),
            ],
            options={
                'abstract': False,
            },
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
>>>>>>> 37dac2585a83b08b1446e1c5dc0bcc315c31b66d
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
    ]
