# Generated by Django 5.2.5 on 2025-09-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head_of_department',
            new_name='hod',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='established_year',
            new_name='establishedYear',
        ),
    ]
