# Generated by Django 5.2.5 on 2025-09-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_created_at_college_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='courseId',
        ),
    ]
